# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://WillSchwieder.github.io/'
baseurl:             'learningjournal/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Will Schwieder
  url:               https://twitter.com/WillSchwieder
  email:             wschwied@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
